# Final Project Part 3
- DataViz, Spring 2020
- Author: Tzu-Kun Hsiao
- NetID: tkhsiao2

In [1]:
import pandas as pd
import numpy as np
import bqplot
import matplotlib.pyplot as plt
import matplotlib
import ipywidgets
from ipywidgets import Layout
import geopandas


%matplotlib inline

# 1. Central interactive visualization featuring the primary dataset

## 1.1 Import dataset and get the subset of 30 most common clinical conditions
- Dataset: [State Summary of Inpatient Charge Data by Medicare Severity Diagnosis Related Group (MS-DRG), FY2017](https://data.cms.gov/Medicare-Inpatient/State-Summary-of-Inpatient-Charge-Data-by-Medicare/q5hc-zvkx)


- The dataset contains 736 clinical conditions. The number of clinical conditions is too large for making a meaningful plot. Hence, in this project, only the 30 most common clinical conditions are selected as the subjects of interest for making the plot.

In [2]:
data = pd.read_csv("ProjectData/State_Summary_of_Inpatient_Charge_Data_by_Medicare_Severity_Diagnosis_Related_Group__MS-DRG___FY2017.csv")
data = data.round(2)

data['drg_id'] = data['DRG Definition'].str.split(' - ').str[0].str.strip()
data['drg_name'] = data['DRG Definition'].str.split(' - ').str[1].str.strip()


print(data.shape)
print(data.count())
print(data.nunique())

data.head()

(27543, 8)
DRG Definition               27543
Provider State               27543
Total Discharges             27543
Average Covered Charges      27543
Average Total Payments       27543
Average Medicare Payments    27543
drg_id                       27543
drg_name                     27543
dtype: int64
DRG Definition                 736
Provider State                  51
Total Discharges              2395
Average Covered Charges      27510
Average Total Payments       27381
Average Medicare Payments    27368
drg_id                         736
drg_name                       736
dtype: int64

,DRG Definition,Provider State,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments,drg_id,drg_name
0,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,OR,11,561665.00,281456.09,229310.82,001,HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SY...
1,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,MD,13,324398.00,299865.77,279902.00,001,HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SY...
2,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,UT,13,597063.69,231009.08,215347.08,001,HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SY...
3,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,MS,14,814803.86,206432.86,193311.14,001,HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SY...
4,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,AL,16,875798.44,249810.06,125897.38,001,HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SY...

In [3]:
data.describe().round(2)

,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments
count,27543.00,27543.00,27543.00,27543.00
mean,349.52,67967.66,17415.74,14695.23
std,1250.61,73462.97,18357.60,16179.96
min,11.00,4445.22,2834.77,1999.08
25%,29.00,29001.01,7886.54,6185.24
50%,75.00,46451.97,11950.43,9847.71
75%,238.00,78801.01,19664.98,16797.60
max,63412.00,1831198.83,351416.79,329469.14

In [4]:
discharge_count = data.groupby(['drg_id'])[['Total Discharges']].sum()
discharge_count = discharge_count.rename(columns={'Total Discharges':'sum_of_total_discharges'})
discharge_count = discharge_count.sort_values(['sum_of_total_discharges'], ascending=False)
discharge_top30 = discharge_count.head(30)
discharge_top30

        sum_of_total_discharges
drg_id
871                      598649
470                      511763
291                      361006
190                      217482
189                      168238
872                      160020
392                      158685
690                      141441
683                      137183
378                      134270
682                      112820
065                      112379
603                      110072
292                      109090
193                      108097
194                      103886
309                       91196
191                       90347
641                       89274
247                       87974
689                       85597
853                       82328
280                       81903
064                       80984
481                       79912
460                       79008
885                       74406
640                       73219
312                       73034
308                       72903

In [5]:
#data[['state_desc', 'drg_desc_id']].groupby(['state_desc']).count()

In [6]:
#data.drg_desc_name.unique()

In [7]:
data.columns

Index(['DRG Definition', 'Provider State', 'Total Discharges',
       'Average Covered Charges', 'Average Total Payments',
       'Average Medicare Payments', 'drg_id', 'drg_name'],
      dtype='object')

In [8]:
data_subset = data.loc[data.drg_id.isin(discharge_top30.index)].copy()
print(data_subset.shape)
print(data_subset.count())
print(data_subset.nunique())

data_subset.head()

(1530, 8)
DRG Definition               1530
Provider State               1530
Total Discharges             1530
Average Covered Charges      1530
Average Total Payments       1530
Average Medicare Payments    1530
drg_id                       1530
drg_name                     1530
dtype: int64
DRG Definition                 30
Provider State                 51
Total Discharges             1298
Average Covered Charges      1530
Average Total Payments       1529
Average Medicare Payments    1528
drg_id                         30
drg_name                       30
dtype: int64

,DRG Definition,Provider State,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments,drg_id,drg_name
1773,064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFA...,WY,60,30648.02,15041.63,13974.37,064,INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION...
1774,064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFA...,VT,135,34225.96,15740.94,13847.07,064,INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION...
1775,064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFA...,AK,143,90033.17,20097.44,18608.55,064,INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION...
1776,064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFA...,RI,242,67740.71,19552.56,17194.55,064,INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION...
1777,064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFA...,MT,243,32401.18,11705.04,10407.91,064,INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION...

## 1.2 Transform data into a numpy 3-D array for making the interactive visualization

In [9]:
def tranport_data(data_df, col_vals, idx_vals, val_column):
    df_temp = pd.DataFrame(columns=col_vals, index=idx_vals).fillna(0)

    for col_val in col_vals:
        data_slice = data_df.loc[data_df['drg_id'] == col_val]
        df_vals = data_slice[['Provider State', val_column]].values.tolist()
        for val_pair in df_vals:
            df_temp.at[val_pair[0], col_val] = val_pair[1]
    
    return df_temp

In [10]:
grid_vals_array = np.empty((51, 31))

states = data_subset['Provider State'].unique().tolist()
states.sort()
drg = data_subset['drg_id'].unique().tolist()
drg.sort()
cost_items = ['Average Covered Charges', 'Average Total Payments', 'Average Medicare Payments']

discharges = tranport_data(data_subset, drg, states, 'Total Discharges')
print(discharges.shape)
covered_charges = tranport_data(data_subset, drg, states, 'Average Covered Charges')
print(covered_charges.shape)
total_payments = tranport_data(data_subset, drg, states, 'Average Total Payments')
print(total_payments.shape)
medicare_payments = tranport_data(data_subset, drg, states, 'Average Medicare Payments')
print(medicare_payments.shape)

discharges = discharges.to_numpy()
covered_charges = covered_charges.to_numpy()
total_payments = total_payments.to_numpy()
medicare_payments = medicare_payments.to_numpy()

grid_vals_array = np.concatenate((discharges, covered_charges, total_payments, medicare_payments), axis=0)
grid_vals_array = grid_vals_array.reshape((4, 51, 30))

grid_vals_array.shape

(51, 30)
(51, 30)
(51, 30)
(51, 30)

(4, 51, 30)

In [11]:
#discharges

In [12]:
#grid_vals_array[0:, :, :]

In [13]:
#grid_vals_array[0, :, :]

In [14]:
#grid_vals_array.max()

In [15]:
#np.arange(1, 32)

In [16]:
#grid_vals_array[0, :, :]

In [17]:
#grid_vals_array[0, :, :]+0.00001

## 1.3 Plot the interactive visualization

In [36]:
# CREATE LABEL - 1
mySelectedLabel = ipywidgets.Label()

# CREATE HEATMAP ELEMENTS -2 
# scale
x_sc = bqplot.OrdinalScale()
y_sc = bqplot.OrdinalScale()
c_sc = bqplot.ColorScale(scheme='BuPu')

# axis
x_ax = bqplot.Axis(scale=x_sc, tick_rotate=90, label='DRG_codes', 
                   tick_style={'font-size': 10})
y_ax = bqplot.Axis(scale=y_sc, orientation='vertical', label = 'State', 
                   tick_style={'font-size': 10})
c_ax = bqplot.ColorAxis(scale=c_sc, orientation='vertical', side='right')

# mark
heat_map = bqplot.GridHeatMap(color = grid_vals_array[0, :, :]/grid_vals_array[0, :, :].max(), 
                              scales = {'color':c_sc, 'row':y_sc, 'column': x_sc}, 
                              interactions = {'click':'select'},
                              anchor_style = {'fill':'blue'}, 
                              row=states, column=drg, 
                              stroke='white')


# CREATE LINE PLOT ELEMENTS -3
# scale
x_scl = bqplot.OrdinalScale()
y_scl = bqplot.LinearScale(min=0, max=grid_vals_array.max()/1000) # set range of y
c_scl = bqplot.ColorScale()

# axis
x_axl = bqplot.Axis(scale=x_scl, tick_rotate=10, grid_lines='none')

y_axl = bqplot.Axis(scale=y_scl, tick_format='0.2f', orientation='vertical',
                    label='US dollars (in thousands)')
c_axl = bqplot.ColorAxis(scale=c_scl)

# mark
bar_ticks = ['covered_charges', 'total_payments', 'medicare_payments']
bar_plot = bqplot.Bars(x = bar_ticks, y = np.arange(3)*0,
                       colors = ['#609EFC'],
                       scales = {'y':y_scl, 'x': x_scl})

# LINKING LINE PLOT WITH HEATMAP -4
def on_selected_3d(change):
    if len(change['owner'].selected) == 1: # only 1 selection per time allowed
        j, i = change['owner'].selected[0] # get x & y indices
        #print(j, i)
        v = grid_vals_array[0, j, i] #grab data value at the (x, y) location (i.e., data points of each year)
        mySelectedLabel.value = 'Discharges = ' + str(v)
        # now including updates to the line plot
        bar_plot.y = np.array([grid_vals_array[1, j, i]/1000, 
                               grid_vals_array[2, j, i]/1000, 
                               grid_vals_array[3, j, i]/1000])

# create interaction through "observe"
heat_map.observe(on_selected_3d, 'selected')

# CREATE FIG OBJECT - 5
fig_heatmap = bqplot.Figure(marks=[heat_map], axes=[c_ax, x_ax, y_ax])
fig_bar = bqplot.Figure(marks=[bar_plot], axes=[x_axl, y_axl])

fig_heatmap.layout.min_width='600px'
fig_heatmap.layout.min_height='600px'

fig_bar.layout.min_width='400px'
fig_bar.layout.min_height='600px'


plots = ipywidgets.HBox([fig_heatmap, fig_bar], layout=Layout(width='100%', height='100%'))

myDashboard = ipywidgets.VBox([mySelectedLabel, plots], layout=Layout(width='100%', height='100%'))
myDashboard

VBox(children=(Label(value=''), HBox(children=(Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale…

# Import contextual dataset

- Dataset: [Inpatient Prospective Payment System (IPPS) Provider Summary for All Diagnosis-Related Groups (DRG) - FY2017](https://data.cms.gov/Medicare-Inpatient/Inpatient-Prospective-Payment-System-IPPS-Provider/tcsp-6e99)

In [19]:
contxt_data = pd.read_csv('ProjectData/Inpatient_Prospective_Payment_System__IPPS__Provider_Summary_for_All_Diagnosis-Related_Groups__DRG__-_FY2017.csv')
contxt_data['Provider Id'] = contxt_data['Provider Id'].astype(str)

contxt_data['drg_id'] = contxt_data['DRG Definition'].str.split(' - ').str[0].str.strip()
contxt_data['drg_name'] = contxt_data['DRG Definition'].str.split(' - ').str[1].str.strip()

print(contxt_data.shape)
contxt_data.head()

(196325, 14)

,DRG Definition,Provider Id,Provider Name,Provider Street Address,Provider City,Provider State,Provider Zip Code,Hospital Referral Region (HRR) Description,Total Discharges,Average Covered Charges,Average Total Payments,Average Medicare Payments,drg_id,drg_name
0,023 - CRANIOTOMY W MAJOR DEVICE IMPLANT OR ACU...,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,28,117117.79,25823.71,24057.39,023,CRANIOTOMY W MAJOR DEVICE IMPLANT OR ACUTE CNS...
1,025 - CRANIOTOMY & ENDOVASCULAR INTRACRANIAL P...,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,32,98357.56,20688.34,19791.41,025,CRANIOTOMY & ENDOVASCULAR INTRACRANIAL PROCEDU...
2,027 - CRANIOTOMY & ENDOVASCULAR INTRACRANIAL P...,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,11,69153.55,11811.18,8194.36,027,CRANIOTOMY & ENDOVASCULAR INTRACRANIAL PROCEDU...
3,037 - EXTRACRANIAL PROCEDURES W MCC,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,12,100427.33,19134.00,18154.00,037,EXTRACRANIAL PROCEDURES W MCC
4,038 - EXTRACRANIAL PROCEDURES W CC,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,AL - Dothan,17,58199.47,8519.47,6714.88,038,EXTRACRANIAL PROCEDURES W CC

# get subset of contextual data

In [20]:
contxt_data_subset = contxt_data.loc[contxt_data.drg_id.isin(data_subset.drg_id.unique().tolist())].copy()

# print(contxt_data_subset.shape)
# print(contxt_data_subset.count())
# print(contxt_data_subset.nunique())

# contxt_data_subset.head()

## contextual visualizations 1

In [21]:

x_choices = contxt_data_subset['Provider State'].unique().tolist()

gdf_states = geopandas.read_file('https://www2.census.gov/geo/tiger/TIGER2019/STATE/tl_2019_us_state.zip')
charge_in_states = contxt_data_subset[['Provider State', 'Total Discharges']].groupby(['Provider State']).sum().reset_index()
charge_in_states = charge_in_states.rename(columns={'Provider State':'STUSPS'})
gdf_states = gdf_states.merge(charge_in_states, how='left')
gdf_states['Total Discharges'] = gdf_states['Total Discharges'].fillna(0)
cmap = plt.cm.BuPu
norm = matplotlib.colors.Normalize(vmin=gdf_states['Total Discharges'].min(), 
                                   vmax=gdf_states['Total Discharges'].max())

@ipywidgets.interact(State=x_choices)
def plot_bars(State):    
    state_subset = contxt_data_subset.loc[contxt_data_subset['Provider State'] == State]
    state_subset = state_subset.groupby(['Provider City'])[['Total Discharges']].sum()
    state_subset = state_subset.sort_values(by = ['Total Discharges'])
        
    x_val = state_subset.index
    y_val = state_subset['Total Discharges']

    fig, ax = plt.subplots(1, 2, figsize=(20, 10))
    
    gdf_states.plot(ax=ax[0], color=cmap(norm(gdf_states['Total Discharges'].values)))
    ax[0].set_xlim(-180, -60) # lat
    ax[0].set_ylim(15, 75) # lon
    sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
    plt.colorbar(sm, ax=ax[0])
    
    ax[1].barh(x_val, y_val, color='#165A69', height=0.8)
    
    ax[1].set_xlabel('Total Discharges in the Cities in '+ State, size=14)
    
    fig.tight_layout()

    plt.xticks(rotation=90, size=14)
    plt.show()

interactive(children=(Dropdown(description='State', options=('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', '…

In [25]:
#contxt_data_subset.head()

In [26]:
#contxt_data_subset.columns

In [37]:

x_choices = contxt_data_subset['Provider State'].unique().tolist()

@ipywidgets.interact(State=x_choices)
def plot_lines(State):
    
    include_cols = ['Average Covered Charges', 'Average Total Payments', 'Average Medicare Payments']
    
    state_subset = contxt_data_subset.loc[contxt_data_subset['Provider State'] == State]
    state_subset = state_subset.groupby(['Provider City'])[include_cols].mean()
    
    fig, ax = plt.subplots(figsize=(14, 8))
    ax.set_xlabel('Cities in '+ State, size=14)
    ax.set_ylabel('Charges/Payment', size=14)
        
    ax.plot(state_subset.index, state_subset['Average Covered Charges'], color='#165A69', linestyle='-')
    ax.plot(state_subset.index, state_subset['Average Total Payments'], color='#165A69', linestyle='-.')
    ax.plot(state_subset.index, state_subset['Average Medicare Payments'], color='#165A69', linestyle=':')
    
    ax.legend(include_cols)

    plt.xticks(rotation=90, size=12)
    plt.show()

interactive(children=(Dropdown(description='State', options=('AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', '…